// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'column-label'
  | 'menu-collection-update'
  | 'menu-item-update'
  | 'menu-library-update'
  | 'pref-auto-tag-on-add'
  | 'pref-help'
  | 'pref-mark-review'
  | 'pref-tag-prefix'
  | 'pref-title'
  | 'prefs-title'
  | 'progress-finished'
  | 'progress-updating';
