// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "autoTagOnAdd": boolean;
      "tagPrefix": string;
      "markReview": boolean;
    };
  }
}
