/**
 * Regenerate src/data/catalog.ts from the verified catalog JSON.
 *
 * Usage:
 *   node tools/sync-data.mjs [path-to-catalog.json]
 *
 * Default source: ../wmu-catalog/data/catalog.json (the wmu-catalog pipeline).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const src =
  process.argv[2] ||
  path.resolve(root, "..", "wmu-catalog", "data", "catalog.json");
const out = path.resolve(root, "src", "data", "catalog.ts");

const data = JSON.parse(fs.readFileSync(src, "utf8"));
if (!Array.isArray(data.journals) || !data.journals.length) {
  throw new Error(`No journals found in ${src}`);
}

const meta = JSON.stringify(data.meta, null, 2);
const journals = data.journals
  .map(
    (j) =>
      `  { name: ${JSON.stringify(j.name)}, issn: ${JSON.stringify(j.issn)}, category: ${JSON.stringify(j.category)}, isReview: ${j.isReview === true} },`,
  )
  .join("\n");

const content = `// Generated by tools/sync-data.mjs from wmu-catalog/data/catalog.json.
// Do not edit manually; re-run the sync script instead.
import type { CatalogEntry } from "../modules/types";

export const catalogMeta = ${meta} as const;

export const catalogJournals: CatalogEntry[] = [
${journals}
];
`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, content, "utf8");
console.log(
  `synced ${data.journals.length} journals from ${src}\n      -> ${out}`,
);
